"""Phase 2 initial migration

Revision ID: 4296ca707f69
Revises: None
Create Date: 2026-09-01 20:27:32.305683

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '4296ca707f69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('local_name_hindi', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('perishability', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='perishabilitytier'), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('standard_unit', sa.String(length=20), nullable=True),
    sa.Column('indicative_base_price_per_kg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('FARMER', 'FPO', 'BULK_BUYER', 'CONSUMER', 'LOGISTICS_PARTNER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('organization_name', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('sub_district', sa.String(length=80), nullable=True),
    sa.Column('village_or_area', sa.String(length=120), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('available_stocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('farmer_id', sa.String(), nullable=False),
    sa.Column('crop_id', sa.String(), nullable=False),
    sa.Column('available_quantity_kg', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('shelf_life_remaining_days', sa.Integer(), nullable=False),
    sa.Column('quality_grade', sa.Enum('GRADE_A', 'GRADE_B', 'ORGANIC', 'EXPORT', name='qualitygrade'), nullable=True),
    sa.Column('location_latitude', sa.Float(), nullable=False),
    sa.Column('location_longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', name='stockstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('posted_by_user_id', sa.String(), nullable=False),
    sa.Column('crop_id', sa.String(), nullable=False),
    sa.Column('required_quantity_kg', sa.Float(), nullable=False),
    sa.Column('max_price_per_kg', sa.Float(), nullable=False),
    sa.Column('target_delivery_date', sa.Date(), nullable=False),
    sa.Column('quality_requirement', sa.Enum('GRADE_A', 'GRADE_B', 'ORGANIC', 'EXPORT', name='qualitygrade'), nullable=True),
    sa.Column('is_bulk_demand', sa.Boolean(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('delivery_latitude', sa.Float(), nullable=False),
    sa.Column('delivery_longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_MATCHED', 'MATCHED', 'FULFILLED', 'CANCELLED', name='demandstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expected_supplies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('farmer_id', sa.String(), nullable=False),
    sa.Column('crop_id', sa.String(), nullable=False),
    sa.Column('expected_quantity_kg', sa.Float(), nullable=False),
    sa.Column('expected_harvest_date', sa.Date(), nullable=False),
    sa.Column('min_price_per_kg', sa.Float(), nullable=False),
    sa.Column('quality_grade', sa.Enum('GRADE_A', 'GRADE_B', 'ORGANIC', 'EXPORT', name='qualitygrade'), nullable=True),
    sa.Column('farm_latitude', sa.Float(), nullable=False),
    sa.Column('farm_longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DECLARED', 'MATCHED', 'HARVESTED', 'CANCELLED', name='supplystatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('DEMAND_ALERT', 'HARVEST_MATCH', 'ORDER_UPDATE', 'PRICE_ALERT', 'LOGISTICS_DISPATCH', name='notificationtype'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('related_entity_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('demand_id', sa.String(), nullable=True),
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('matched_crop_id', sa.String(), nullable=False),
    sa.Column('total_matched_quantity_kg', sa.Float(), nullable=False),
    sa.Column('agreed_farmer_price_per_kg', sa.Float(), nullable=False),
    sa.Column('total_amount_inr', sa.Float(), nullable=False),
    sa.Column('participating_farmer_ids', sa.JSON(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'CONFIRMED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='matchstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['demand_id'], ['demand_posts.id'], ),
    sa.ForeignKeyConstraint(['matched_crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_breakdowns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('crop_id', sa.String(), nullable=False),
    sa.Column('farmer_price_per_kg', sa.Float(), nullable=False),
    sa.Column('collection_handling_fee', sa.Float(), nullable=False),
    sa.Column('transport_fee_per_kg', sa.Float(), nullable=False),
    sa.Column('market_intermediary_margin', sa.Float(), nullable=True),
    sa.Column('platform_coordination_fee', sa.Float(), nullable=False),
    sa.Column('final_consumer_price_per_kg', sa.Float(), nullable=False),
    sa.Column('farmer_net_realization_per_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['order_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('logistics_partner_id', sa.String(), nullable=True),
    sa.Column('pickup_waypoints', sa.JSON(), nullable=False),
    sa.Column('drop_waypoint', sa.JSON(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_transit_hours', sa.Float(), nullable=False),
    sa.Column('route_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['logistics_partner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['order_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_routes')
    op.drop_table('price_breakdowns')
    op.drop_table('order_matches')
    op.drop_table('notifications')
    op.drop_table('expected_supplies')
    op.drop_table('demand_posts')
    op.drop_table('available_stocks')
    op.drop_table('users')
    op.drop_table('crops')
    # ### end Alembic commands ###
